name: build

# Build and test databento-cpp

on:
  push:
    branches: [main, dev]

jobs:
  ubuntu:
    strategy:
      fail-fast: false
      matrix:
        compiler: [clang++, g++]

    name: build - ubuntu-latest - ${{ matrix.compiler}}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install cppcheck libzstd-dev ninja-build
      - name: Install gtest
        uses: MarkusJx/googletest-installer@v1.1
      - name: CMake configure
        run: |
          cmake -S . -B build \
            -GNinja \
            -DCMAKE_CXX_COMPILER=${{ matrix.compiler }} \
            -DDATABENTO_ENABLE_UNIT_TESTING=1 \
            -DDATABENTO_ENABLE_EXAMPLES=1 \
            -DDATABENTO_ENABLE_CLANG_TIDY=1 \
            -DDATABENTO_ENABLE_CPPCHECK=1 \
            -DDATABENTO_ENABLE_ASAN=1 \
            -DDATABENTO_ENABLE_UBSAN=1
      - name: CMake build
        run: cmake --build build
      - name: Unit tests
        run: cd build && ctest --verbose

  macos:
    name: build - macos-latest - clang++
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install dependencies
        run: brew install cmake cppcheck googletest openssl@3 ninja zstd
      # Don't enable clang-tidy on macOS because it's incredibly slow
      - name: CMake configure
        run: |
          cmake -S . -B build \
            -GNinja \
            -DDATABENTO_ENABLE_UNIT_TESTING=1 \
            -DDATABENTO_ENABLE_EXAMPLES=1 \
            -DDATABENTO_ENABLE_CPPCHECK=1 \
            -DDATABENTO_ENABLE_TSAN=1 \
            -DOPENSSL_ROOT_DIR=$(brew --prefix openssl@3)
      - name: CMake build
        run: cmake --build build
      - name: Unit tests
        run: cd build && ctest --verbose
